In [23]:
from pathlib import Path
import os
from streettransformer.alignment.validate import (
    validation_table, 
    validate_classifier,
    validate_identifier,
    validate_summarizer,
    validate_dater,
    bulk_validate
)

# Summarizers

In [24]:
import pandas as pd
results = {}

results['summarizer'] = pd.DataFrame({
    ('image-to-document', 'gpt-4o'): validate_summarizer('summarizer-image-4o.csv', 'summarizer-document-4o.csv'),
    ('sidebyside-to-document', 'gpt-4o'): validate_summarizer('summarizer-sidebyside-4o.csv', 'summarizer-document-4o.csv'),
    ('image-to-sidebyside', 'gpt-4o'): validate_summarizer('summarizer-image-4o.csv', 'summarizer-sidebyside-4o.csv')
}).T.reset_index(names=['format', 'model']).to

# Classifiers

In [25]:
INPUTS = {
    ('image', 'gpt-4o'): 'identifier-image-4o.csv',
    ('sidebyside', 'gpt-4o'): 'identifier-sidebyside-4o.csv',
    ('image', 'gpt-5'): 'identifier-image-5.csv',
    ('sidebyside', 'gpt-5'): 'identifier-sidebyside-5.csv'
}

results['classifier'] = bulk_validate(
    inputs=INPUTS,
    validation_function=validate_classifier,
    groundtruth_path='change_classifier.parquet',
    true_class_col='class',
    pred_class_col= 'change_detected'
)

116 NA records removed
     location_id year_start year_end pred_class  true_class
0            604       2006     2014      False       False
1           3047       2006     2018      False       False
2           3893       2006     2014      False       False
3           3893       2012     2018       True       False
4           4317       2006     2024       True        True
..           ...        ...      ...        ...         ...
991      9065997       2012     2014       True       False
992      9066199       2014     2024      False       False
993      9066221       2006     2024       True        True
995      9066224       2014     2024       True        True
996      9066225       2006     2012       True       False

[881 rows x 5 columns]
74 NA records removed
     location_id year_start year_end pred_class  true_class
0            604       2006     2014      False       False
1           3047       2006     2018       True       False
2           3893       2006     2014      False       False
3           3893       2012     2018       True       False
4           4317       2006     2024       True        True
..           ...        ...      ...        ...         ...
990      9064661       2006     2018       True       False
991      9065997       2012     2014      False       False
992      9066199       2014     2024       True       False
993      9066221       2006     2024       True        True
994      9066221       2014     2024       True        True

[923 rows x 5 columns]
887 NA records removed
     location_id year_start year_end pred_class  true_class
11          8567       2012     2018      False        True
18          9865       2006     2014      False       False
28         13888       2014     2024       True        True
32         13892       2012     2024       True        True
38         15077       2014     2024       True        True
..           ...        ...      ...        ...         ...
935      9051208       2012     2024       True        True
937      9051252       2012     2024       True       False
967      9060389       2012     2024       True        True
973      9062701       2014     2024       True       False
978      9063608       2006     2018       True        True

[100 rows x 5 columns]
887 NA records removed
     location_id year_start year_end pred_class  true_class
11          8567       2012     2018      False        True
18          9865       2006     2014       True       False
28         13888       2014     2024       True        True
32         13892       2012     2024       True        True
38         15077       2014     2024       True        True
..           ...        ...      ...        ...         ...
935      9051208       2012     2024       True        True
937      9051252       2012     2024       True       False
967      9060389       2012     2024       True        True
973      9062701       2014     2024       True       False
978      9063608       2006     2018       True        True

[100 rows x 5 columns]

In [15]:
for _, i in INPUTS.items():
    classifier = i.replace('identifier', 'classifier')
    validation_table(
        i,
        groundtruth_path='change_classifier.parquet',
        true_class_col='class',
        pred_class_col= 'change_detected'
    ).to_csv(f'../data/exports/data_help/validation_tables/{classifier}', index=False)

    validation_table(
        i,
        groundtruth_path='change_identifier.parquet',
        true_class_col='correct_tags',
        pred_class_col= 'features'
    ).to_csv(f'../data/exports/data_help/validation_tables/{i}', index=False)

116 NA records removed
133 NA records removed
74 NA records removed
91 NA records removed
887 NA records removed
871 NA records removed
887 NA records removed
871 NA records removed

# Identifiers

In [26]:
results['identifier'] = bulk_validate(
    inputs=INPUTS,
    validation_function=validate_identifier,
    groundtruth_path='change_identifier.parquet',
    true_class_col='correct_tags',
    pred_class_col= 'features'
)

133 NA records removed
     location_id year_start year_end  \
0            604       2006     2014
1           3047       2006     2018
2           3893       2006     2014
3           3893       2012     2018
4           4317       2006     2024
..           ...        ...      ...
990      9064661       2006     2018
991      9065997       2012     2014
993      9066221       2006     2024
995      9066224       2014     2024
996      9066225       2006     2012

                                            pred_class  \
0                                                   []
1                                                   []
2                                                   []
3                 [Curb Extensions, Sidewalk Redesign]
4    [Curb Extensions, New or Expanded Median/Pedes...
..                                                 ...
990  [Lane Removal or Road Narrowing, Sidewalk Rede...
991  [New or Expanded Median/Pedestrian Refuge Isla...
993  [New or Expanded Median/Pedestrian Refuge Island]
995                   [Lane Removal or Road Narrowing]
996                                  [Curb Extensions]

                                            true_class
0                                                   []
1                                                   []
2                                                   []
3                                                   []
4                                      [Raised Median]
..                                                 ...
990                                                 []
991                                                 []
993  [New or Expanded Median/Pedestrian Refuge Isla...
995  [New or Expanded Median/Pedestrian Refuge Isla...
996                                                 []

[864 rows x 5 columns]
91 NA records removed
     location_id year_start year_end  \
0            604       2006     2014
1           3047       2006     2018
2           3893       2006     2014
3           3893       2012     2018
4           4317       2006     2024
..           ...        ...      ...
990      9064661       2006     2018
991      9065997       2012     2014
993      9066221       2006     2024
994      9066221       2014     2024
995      9066224       2014     2024

                                            pred_class  \
0                                                   []
1    [New or Expanded Median/Pedestrian Refuge Island]
2                                                   []
3    [New or Expanded Median/Pedestrian Refuge Isla...
4                                    [Curb Extensions]
..                                                 ...
990               [Sidewalk Redesign, Curb Extensions]
991                                                 []
993  [Curb Extensions, New or Expanded Median/Pedes...
994  [Lane Removal or Road Narrowing, New or Expand...
995  [Lane Removal or Road Narrowing, Sidewalk Rede...

                                            true_class
0                                                   []
1                                                   []
2                                                   []
3                                                   []
4                                      [Raised Median]
..                                                 ...
990                                                 []
991                                                 []
993  [New or Expanded Median/Pedestrian Refuge Isla...
994  [New or Expanded Median/Pedestrian Refuge Isla...
995  [New or Expanded Median/Pedestrian Refuge Isla...

[906 rows x 5 columns]
871 NA records removed
     location_id year_start year_end  \
11          8567       2012     2018
18          9865       2006     2014
27         13888       2014     2024
31         13892       2012     2024
37         15077       2014     2024
..           ...        ...      ...
919      9051208       2012     2024
921      9051252       2012     2024
951      9060389       2012     2024
957      9062701       2014     2024
962      9063608       2006     2018

                                            pred_class  \
11                                                  []
18                                                  []
27                                   [Curb Extensions]
31                                   [Curb Extensions]
37            [Bike Enhancement, Median Tip Extension]
..                                                 ...
919  [New or Expanded Median/Pedestrian Refuge Isla...
921               [Curb Extensions, Sidewalk Redesign]
951  [Raised Median, New or Expanded Median/Pedestr...
957  [Curb Extensions, New or Expanded Median/Pedes...
962  [Bike Enhancement, Median Tip Extension, New o...

                                            true_class
11   [Curb Extensions, Raised Median, Median Tip Ex...
18                                                  []
27   [Bus Bulb, Sidewalks, Raised Median, Curb Exte...
31   [Bus Bulb, Sidewalks, Raised Median, Curb Exte...
37      [Curb Extensions, Plaza/Ped Space Enhancement]
..                                                 ...
919  [Lane Removal or Road Narrowing, Sidewalks, Pl...
921                                        [Sidewalks]
951         [Bus Bulb, Raised Median, Curb Extensions]
957                                                 []
962  [New or Expanded Median/Pedestrian Refuge Isla...

[99 rows x 5 columns]
871 NA records removed
     location_id year_start year_end  \
11          8567       2012     2018
18          9865       2006     2014
27         13888       2014     2024
31         13892       2012     2024
37         15077       2014     2024
..           ...        ...      ...
919      9051208       2012     2024
921      9051252       2012     2024
951      9060389       2012     2024
957      9062701       2014     2024
962      9063608       2006     2018

                                            pred_class  \
11                                                  []
18                                   [Curb Extensions]
27   [Curb Extensions, New or Expanded Median/Pedes...
31   [Curb Extensions, Lane Removal or Road Narrowing]
37                 [Bike Enhancement, Curb Extensions]
..                                                 ...
919  [Curb Extensions, New or Expanded Median/Pedes...
921                                  [Curb Extensions]
951  [New or Expanded Median/Pedestrian Refuge Isla...
957  [Curb Extensions, New or Expanded Median/Pedes...
962  [Median Tip Extension, New or Expanded Median/...

                                            true_class
11   [Curb Extensions, Raised Median, Median Tip Ex...
18                                                  []
27   [Bus Bulb, Sidewalks, Raised Median, Curb Exte...
31   [Bus Bulb, Sidewalks, Raised Median, Curb Exte...
37      [Curb Extensions, Plaza/Ped Space Enhancement]
..                                                 ...
919  [Lane Removal or Road Narrowing, Sidewalks, Pl...
921                                        [Sidewalks]
951         [Bus Bulb, Raised Median, Curb Extensions]
957                                                 []
962  [New or Expanded Median/Pedestrian Refuge Isla...

[99 rows x 5 columns]

# Daters

In [ ]:
from streettransformer.alignment.validate import DaterKey, DaterOutput
from dataclasses import fields

val_df_sbs_4o = validation_table(
    'dater-sidebyside-4o.csv',
    'dater.parquet',
    'proj_year',
    'change_locations',
    DaterKey, 
    DaterOutput
)

val_df_img_4o = validation_table(
    'dater-image-4o.csv',
    'dater.parquet',
    'proj_year',
    'change_locations',
    DaterKey, 
    DaterOutput
)


val_df_sbs_5 = validation_table(
    'dater-sidebyside-5.csv',
    'dater.parquet',
    'proj_year',
    'change_locations',
    DaterKey, 
    DaterOutput
)

val_df_img_5 = validation_table(
    'dater-image-5.csv',
    'dater.parquet',
    'proj_year',
    'change_locations',
    DaterKey, 
    DaterOutput
)

# validate_dater(val_df,
#                'proj_year','change_locations')

INPUTS = {
    ('image', 'gpt-4o'): 'dater-image-4o.csv',
#    ('sidebyside', 'gpt-4o'): 'dater-sidebyside-4o.csv'
}

# results['dater'] = bulk_validate(
# # bulk_validate(
#     inputs=INPUTS,
#     validation_function=validate_identifier,
#     groundtruth_path='dater.parquet',
#     true_class_col='proj_year',
#     pred_class_col= 'change_locations',
#     key_obj=DaterKey,
#     results_obj=DaterOutput
# )

val_df_img_4o.to_csv('../data/exports/metrics/validations/dater_image_4o.csv')
val_df_sbs_4o.to_csv('../data/exports/metrics/validations/dater_sbs_4o.csv')
val_df_img_5.to_csv('../data/exports/metrics/validations/dater_image_5.csv')
val_df_sbs_5.to_csv('../data/exports/metrics/validations/dater_sb_5.csv')

1404 NA records removed
1262 NA records removed
1624 NA records removed
1604 NA records removed

In [30]:
results['summarizer'].to_csv('../data/exports/metrics/summarizer.csv')

In [37]:
results['classifier'].to_csv('../data/exports/metrics/classifier.csv')

In [38]:
results['identifier'].to_csv('../data/exports/metrics/identifier.csv')
# validation_table(
#     'identifier-image-4o.csv',
#     'change_identifier.parquet',
#     true_class_col='correct_tags',
#     pred_class_col= 'features'
# )

In [ ]:
results['dater']
#val_df_img

KeyError: 'dater'

In [ ]:
from streettransformer.llms.queries import QUERIES
print(QUERIES['image_change_dater'].text())

        Role: You are a Transportation Engineer employed by the city tasked with analyzing changes in intersection streetscape over time.

        Goal: Your goal is to look at an ordered set of images of the same location across different dates, and identify when the significant infrastrcutural change occured, if it did at all. Limit this analysis to only capital reconstruction features including: 'Curb Extensions', 'New or Expanded Median/Pedestrian Refuge Island', 'Bike Enhancement', 'Median Tip Extension', 'Raised Median', 'Lane Removal or Road Narrowing', 'Bus Bulb', 'Shared Street', 'Sidewalk Redesign')

        Respond: Please respond in a well formatted json exclusively with 2 tags:
	- change_detected: A boolean value if you detect significant change with regards to the above categories. Respond exclusively with True or False
	- change_locations: A list of image IDs that you believe show a significant change from the image before. Please only respond with ['2006', '2012', '2014', '2018', '2024']